config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :users_integrations
  root 'home#index'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/integration.rb
class Integration < ApplicationRecord
    has_many :users_integration
end

app/models/ticket.rb
class Ticket < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/users_integration.rb
class UsersIntegration < ApplicationRecord
    belongs_to :integration
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require "JsonAPI"

class HomeController < ApplicationController
  def index
    integrations = UsersIntegration.where(user_id: current_user.id)
    
    integrations.each do |integration|
      integ = integration.integration.name.capitalize
      @tickets = integ.constantize.new(integration).list
    end

    users_integrations = UsersIntegration.where(id: 4)
    users_integrations.each do |integration|
        instance = Kayako.new(integration)
        @test = instance.fields
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.fetch(:ticket, {})
    end
end

app/controllers/users_integrations_controller.rb
class UsersIntegrationsController < ApplicationController
  before_action :set_users_integration, only: %i[ show edit update destroy ]

  # GET /users_integrations or /users_integrations.json
  def index
    @users_integrations = UsersIntegration.all
  end

  # GET /users_integrations/1 or /users_integrations/1.json
  def show
  end

  # GET /users_integrations/new
  def new
    @users_integration = UsersIntegration.new
    @integrations = Integration.all
  end

  # GET /users_integrations/1/edit
  def edit
  end

  # POST /users_integrations or /users_integrations.json
  def create
    @users_integration = UsersIntegration.new(users_integration_params)

    respond_to do |format|
      if @users_integration.save
        format.html { redirect_to @users_integration, notice: "Users integration was successfully created." }
        format.json { render :show, status: :created, location: @users_integration }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @users_integration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_integrations/1 or /users_integrations/1.json
  def update
    respond_to do |format|
      if @users_integration.update(users_integration_params)
        format.html { redirect_to @users_integration, notice: "Users integration was successfully updated." }
        format.json { render :show, status: :ok, location: @users_integration }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @users_integration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_integrations/1 or /users_integrations/1.json
  def destroy
    @users_integration.destroy
    respond_to do |format|
      format.html { redirect_to users_integrations_url, notice: "Users integration was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_integration
      @users_integration = UsersIntegration.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def users_integration_params
      params.require(:users_integration).permit(:integration_id, :user_id, :name, :uri, :username, :password, )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/date_helper.rb
module DateHelper
    def formatIsoDate(date)
        return Time.parse(date).strftime("%Y-%m-%d %H:%M:%S")  
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_integrations_helper.rb
module UsersIntegrationsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Tickets Zone', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Tickets', tickets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Integrations', users_integrations_path, class: "nav-link" %>          
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Settings</a>
        </li>
      </ul>  
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
        </li>
      </ul>   
    <% else %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: "btn btn-primary mr-2" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: "btn btn-primary" %>
        </li>
      </ul>    
    <% end %>
   
  </div>
</nav>

app/views/home/index.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Integration</th>
      <th scope="col">Ticket ID</th>
      <th scope="col">Ticket Created</th>
      <th scope="col">Ticket Subject</th>
    </tr>
  </thead>
  <tbody>
     <% @tickets.each do |ticket| %>
      <tr>
        <td>Freshdesk</td>
        <td><%= ticket['id'] %></td>
        <td><%= formatIsoDate(ticket['created_at']) %></td>
        <td><%= ticket['subject'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<pre>
  <%= @test.inspect %>
</pre>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body style="background-color: #e3e3e3">
    <%= render "home/header" %>

    <div class="container">
      <header class="text-center">
        <h1 class="mt-4">Tickets Zone</h1>
      </header>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Integration</th>
      <th scope="col">Ticket ID</th>
      <th scope="col">Ticket Created</th>
      <th scope="col">Ticket Subject</th>
    </tr>
  </thead>
  <tbody>
     <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.users_integration.integration.type %></td>
        <td><%= ticket['id'] %></td>
        <td><%= ticket['created_at'] %></td>
        <td><%= ticket['subject'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/users_integrations/_form.html.erb
<div class="panel w-50 mx-auto">
<%= form_with(model: users_integration) do |form| %>
  <% if users_integration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(users_integration.errors.count, "error") %> prohibited this users_integration from being saved:</h2>

      <ul>
        <% users_integration.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
     <%= form.label :integration_id, class: "font-weight-bold" %><br />
    <%= form.collection_select :integration_id, @integrations, :id, :name, {:prompt => "Select an integration"}, {:class=>"form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :name, class: "font-weight-bold" %><br />
    <%= form.text_field :name, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :uri, class: "font-weight-bold" %><br />
    <%= form.text_field :uri, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :username, class: "font-weight-bold" %><br />
    <%= form.text_field :username, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password, class: "font-weight-bold" %><br />
    <%= form.password_field :password, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>

    <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions text-center">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/users_integrations/edit.html.erb
<h1>Editing Users Integration</h1>

<%= render 'form', users_integration: @users_integration %>

<%= link_to 'Show', @users_integration %> |
<%= link_to 'Back', users_integrations_path %>

app/views/users_integrations/index.html.erb
<p id="notice" class="alert alert-success hidden"><%= notice %></p>

<div class="text-center mb-3">
<%= link_to 'Add Integration', new_users_integration_path, class: "btn btn-primary" %>
</div>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Integration Name</th>
      <th scope="col">Integration Type</th>
      <th scope="col">Integration URI</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users_integrations.each do |users_integration| %>
      <tr>
        <td><%= users_integration.id %></td>
        <td><%= users_integration.name %></td>
        <td><%= users_integration.integration.name %></td>
        <td><%= users_integration.uri %></td>
        <td class="text-center">
          <%= link_to 'Show', users_integration, class: "btn btn-success"%>
          <%= link_to 'Edit', edit_users_integration_path(users_integration), class: "btn btn-primary" %>
          <%= link_to 'Destroy', users_integration, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users_integrations/new.html.erb
<%= render 'form', users_integration: @users_integration %>

app/views/users_integrations/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col" colspan="2" class="text-center"><%= @users_integration.name %> (<%= @users_integration.integration.name %>)</th><tr>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Integration Name:</td><td><%= @users_integration.name %></td>
    </tr>
    <tr>
      <td>Integration Type:</td><td><%= @users_integration.integration.name %></td>
    </tr>
        <tr>
      <td>Integration URI:</td><td><%= @users_integration.uri %></td>
    </tr>
        <tr>
      <td>Integration Username:</td><td><%= @users_integration.username %></td>
    </tr>
        <tr>
      <td>Integration Password:</td><td><%= @users_integration.password %></td>
    </tr>
  </tbody>
</table>


<%= link_to 'Edit', edit_users_integration_path(@users_integration) %> |
<%= link_to 'Back', users_integrations_path %>